// web/src/components/quellen-liste.tsx
'use client'

import { ChevronRightIcon, FileTextIcon } from 'lucide-react'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import type { Quelle } from '@/lib/typen'

function prozent(score: number): string {
  return `${Math.round(score * 100)} %`
}

/** Aufklappbare Liste der Absätze, auf die sich eine Antwort stützt. */
export function QuellenListe({ quellen }: { quellen: Quelle[] }) {
  if (quellen.length === 0)
    return null
  return (
    <Collapsible className="mt-2 text-sm">
      <CollapsibleTrigger className="group inline-flex items-center gap-1 rounded-md py-0.5 font-medium text-muted-foreground outline-none hover:text-foreground focus-visible:ring-3 focus-visible:ring-ring/50">
        <ChevronRightIcon aria-hidden className="size-4 transition-transform group-data-panel-open:rotate-90" />
        {quellen.length === 1 ? '1 Quelle' : `${quellen.length} Quellen`}
      </CollapsibleTrigger>
      <CollapsibleContent>
        <ol className="mt-1 flex flex-col gap-2">
          {quellen.map((q, i) => (
            <li key={i} className="border-l-2 border-border pl-2.5">
              <div className="flex justify-between gap-2 font-medium">
                <span className="inline-flex min-w-0 items-center gap-1.5">
                  <FileTextIcon aria-hidden className="size-3.5 shrink-0" />
                  <span className="truncate">{q.titel}</span>
                </span>
                <span className="whitespace-nowrap text-muted-foreground tabular-nums" title="Ähnlichkeit zur Frage">
                  {prozent(q.score)}
                </span>
              </div>
              <blockquote className="mt-0.5 leading-snug text-muted-foreground">{q.absatz}</blockquote>
            </li>
          ))}
        </ol>
      </CollapsibleContent>
    </Collapsible>
  )
}

// web/src/components/QuellenListe.vue
<script setup lang="ts">
import type { Quelle } from '../api'
import { ref } from 'vue'

defineProps<{ quellen: Quelle[] }>()
const offen = ref(false)

function prozent(score: number): string {
  return `${Math.round(score * 100)} %`
}
</script>

<template>
  <div v-if="quellen.length" class="quellen">
    <button type="button" class="quellen-kopf" data-test="quellen-kopf" @click="offen = !offen">
      <i :class="offen ? 'pi pi-chevron-down' : 'pi pi-chevron-right'" />
      {{ quellen.length === 1 ? '1 Quelle' : `${quellen.length} Quellen` }}
    </button>
    <ol v-if="offen" class="quellen-liste">
      <li v-for="(q, i) in quellen" :key="i" class="quelle" data-test="quelle">
        <div class="quelle-kopf">
          <span class="quelle-titel"><i class="pi pi-file" /> {{ q.titel }}</span>
          <span v-tooltip.left="'Ähnlichkeit zur Frage'" class="quelle-score">{{ prozent(q.score) }}</span>
        </div>
        <blockquote class="quelle-absatz">
          {{ q.absatz }}
        </blockquote>
      </li>
    </ol>
  </div>
</template>

<style scoped>
.quellen {
  margin-top: 0.5rem;
  font-size: 0.85rem;
}

.quellen-kopf {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  background: none;
  border: none;
  padding: 0.2rem 0;
  color: var(--p-primary-color);
  cursor: pointer;
  font: inherit;
  font-weight: 500;
}

.quellen-liste {
  margin: 0.25rem 0 0;
  padding: 0;
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.quelle {
  border-left: 3px solid color-mix(in srgb, var(--p-primary-color) 50%, transparent);
  padding-left: 0.6rem;
}

.quelle-kopf {
  display: flex;
  justify-content: space-between;
  gap: 0.5rem;
  font-weight: 500;
}

.quelle-score {
  color: var(--p-text-muted-color);
  font-variant-numeric: tabular-nums;
  white-space: nowrap;
}

.quelle-absatz {
  margin: 0.2rem 0 0;
  color: var(--p-text-muted-color);
  line-height: 1.4;
}
</style>
